api/urls.py
from django.urls import path
from api.views.order_views import *
from api.views.product_views import *
from .views.auth_views import *

urlpatterns = [
    # -- auth API View Urls
    path('register/', RegisterApiView.as_view(), name="register-api"),
    path('login/', LoginApiView.as_view(), name="login-api"),
    path('profile/', ProfileAPIView.as_view(), name="profile-api"),
    path('profile/<int:pk>', ProfileDetailApiView.as_view(), name="profile-detail"),  
     # -- products API View Urls
    path('category-api/', CategoryApiView.as_view(), name="category-api"),
    path('product-api/', ProductApiView.as_view(), name="product-api"),
    path('images-api/', ProductImageApiView.as_view(), name="images-api"),
    path('variation-api/', ProductVariationApiView.as_view(), name="variation-api"),
    path('favorite/add-list/', AddListFavoriteApiView.as_view(), name="add-list-favorite"),
    path('favorite/remove/<int:pk>', RemoveFromFavoriteApiView.as_view(), name="remove-favorite"),
    path('reviews/', ProductReviewApiView.as_view(), name="reviews"),
    # -- orders
    path('cart/cartlist/', CartItemListApiView.as_view(), name="cartlist"),
    path('cart/add-to-cart/', AddToCart.as_view(), name="add-to-cart"),
    path('coupon/', CouponListApiView.as_view(), name="coupon"),
    path('address/', ShippingAddressApiView.as_view(), name="address"),
    path('address/remove/<int:pk>', RemoveShippingAddressApi.as_view(), name="remove-address"),
    path('order/', OrderListApiView.as_view(), name="order-list"),
    path('order/update/<int:pk>', UpdateOrderApiView.as_view(), name="order-update"),
]

ecom_web/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Ecom Web Api View",
      default_version='v2',
      description="Api for Ecom mobile app",
      terms_of_service="https://www.ecom.com/policies/terms/",
      contact=openapi.Contact(email="contact@ecom.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('core.urls')),
    path('auth/', include('authentication.urls')),
    path('api/', include('api.urls')),
    path('swagger', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . views import *


urlpatterns = [
    path('', home, name="home"),
    path('shop/', store, name="store"),
    path('?P<slug:slug>.+?', ProductDetail, name="detail"),
    path('?P<str:title>.+?/', category, name="category"),
    path('?P/s/.+?', search, name="search"),
]

store/models.py
from django.db import models

from authentication.models import User

class ProductCategory(models.Model):
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to='images/products', null=True , blank=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=60, default=0.0, blank=True, null=True)
    discount_price = models.DecimalField(decimal_places=2, max_digits=60, default=0.0, blank=True, null=True)
    category = models.ManyToManyField('ProductCategory', default='uncategorize', related_name='productcategory')
    created_on = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title
        
    class Meta:
        unique_together = ('title', 'slug')


class ProductsImage(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/products')
    featured = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.product_id.title



class VariationManager(models.Model):
    def all(self):
        return super(VariationManager, self).filter(active=True)

    def sizes(self):
        return self.all().filter(category='size')

    def colors(self):
        return self.all().filter(category='color')
    
    def packages(self):
        return self.all().filter(category='package')


VAR_CATEGORY = (
    ('color', 'color'),
    ('size', 'size'),
    ('package', 'package')
)


class Variation(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    category = models.CharField(max_length=120, choices=VAR_CATEGORY, default='size', null=True, blank=True)
    image = models.ForeignKey(ProductsImage, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)
    objects = VariationManager()

    def __str__(self):
        return self.product_id.title


RATE_CHOICES = (
    zip(range(1,6), range(1,6))
)

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)
    like = models.BooleanField(default=False)
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES)
    created_on = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return "Review id %s" %(self.user.name)
    
    
    
class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.name + "  " + self.product.title

api/views/product_views.py
from api.serializers.product_serializers import *
from rest_framework import generics, permissions
from store.models import *


#category list
class CategoryApiView(generics.ListAPIView):
    serializer_class = CategorySerializer
    queryset = ProductCategory.objects.all()
    permission_classes = (permissions.IsAuthenticated,)
    
    
#product list
class ProductApiView(generics.ListAPIView):
    serializer_class = ProductSerializer
    queryset = Product.objects.all()
    permission_classes = (permissions.IsAuthenticated,)
    filter_queryset = ['category']
    
    
#product image
class ProductImageApiView(generics.ListAPIView):
    serializer_class = ImageSerializer
    queryset = ProductsImage.objects.all()
    filter_queryset = ['product']
    
    
#Product variation list    
class ProductVariationApiView(generics.ListAPIView):
    serializer_class = VariationSerializer
    queryset = Variation.objects.all()
    filter_queryset = ['product']
    
    
 #add and lis favorite   
class AddListFavoriteApiView(generics.ListCreateAPIView):
    serializer_class = AddRemoveFavoriteSerializer
    queryset = Favorite.objects.all()
    permission_classes = (permissions.IsAuthenticated,)
    
    def perform_create(self, request):
        return self.serializer_class.save(user=request.user)
    

# remove from favorite    
class RemoveFromFavoriteApiView(generics.DestroyAPIView):
    serializer_class = AddRemoveFavoriteSerializer
    queryset = Favorite.objects.all()
    permission_classes = (permissions.IsAuthenticated,)


# -- Product review
class ProductReviewApiView(generics.ListCreateAPIView):
    serializer_class = ReviewSerializer
    queryset = Review.objects.all()
    permission_classes = (permissions.IsAuthenticated,)
    
    def perform_create(self):
        return self.serializer_class.save()

store/views.py
from datetime import timedelta
from django.shortcuts import render, redirect
from .models import*
from django.db.models import Q


def home(request):
    products = Product.objects.all()
    adproducts = Product.objects.all()
    context = {
        'products': products, 
        'adproducts': adproducts,
    }
    return render(request, 'store/index.html', context)



def ProductDetail(request, slug):
    product = Product.objects.get(slug=slug)
    related = Product.objects.filter(category__title__contains=product.category)
    context = {
        'product': product,
        'related': related,
    }
    return render(request, 'store/singleproduct.html', context)



def store(request):
    context = {
        'items': Product.objects.all().order_by('-id')
    }
    return render(request, 'store/product.html', context)



def category(request, title):
    products = Product.objects.filter(category__title__contains=title)
    context = {
        'products': products
    }
    return render(request, 'store/category.html', context)



def search(request):
    try:
        q = request.Get.get('q')
    except:
        q = None
    if q:
        products = Product.objects.filter(title__icontains=q)
        context = {'query': q, 'products': products}
        return render(request, 'store/search.html', context)
    else:
        context={}   
        return redirect('/')

templates/store/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} Ecom {% endblock %}</title>
        <link  href="{% static 'css/style.css' %}" rel="stylesheet">
        <link  href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
        <link  href="{% static 'css/owl.theme.green.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/stripe.css' %}" />
        <script src="https://js.stripe.com/v3/"></script>
        <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
        <script src="{% static 'js/client.js' %}" defer></script>
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <!-- Google Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    </head>
    <body>
        {% include 'store/menu.html' %}
        <br>
        {% include 'store/searchbar.html' %}

        {% block content %}

        {% endblock %}
        
        {% include 'store/footer.html' %}
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
        <script>
                document.querySelector(".hamburger-menu").
                addEventListener("click", () => {
                document.querySelector('.sidebar').classList.toggle('inactive');
            });

            document.querySelector(".hamburger-menu").
                addEventListener("click", () => {
                document.querySelector('.container').classList.toggle('change');
            });

            $('.home-slider').owlCarousel({
            loop:true,
            margin:10,
            nav:true,
            items:1
            });
        </script>
    </body>
</html>

templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
    <div class="container" style="padding: 5rem 0;">
        <div class="heading_container">
            <h2>
              Cart
            </h2>
        </div>           
        <br>
          {% if empty %}
            <h1>{{ empty_message }}</h1>
            <a href="{% url 'store' %}" class="btn btn-black btn-outline-black float-right ml-2 rounded-1">Start shopping</a>
          {% else %}
            <div class="row">
                <div class="col-lg-12"> 
                    <div class="shop__cart__table">
                        <table class="table table-responsive">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Sub Total</th>
                                </tr>
                            </thead>
                            
                            <tbody>
                                {% for product in cart %}
                                    <tr>
                                        <td class="cart__product__item">
                                            {% for img in product.item.productsimage_set.all %}
                                                {% if img.active %}
                                                <img src="{{ img.image.url }}" alt="" width="100px">
                                                {% endif %}
                                            {% endfor %}
                                            <div class="cart__product__item__title">
                                                <h6>{{ product.item.title }}</h6>
                                            </div>
                                        </td>
                                        {% if product.item.discount_price %}
                                            <td class="cart__price">GHC {{ product.item.discount_price }}</td>
                                        {% else %}
                                            <td class="cart__price">GHC {{ product.item.price }}</td>
                                        {% endif %}
                                        <td class="text-center" style="font-size:20px;">
                                            <a href="{% url 'remove_from_cart' product.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                                            {{ product.quantity }}
                                            <a href="{% url 'add_cart' product.item.slug %}"><i class="fas fa-plus mr-2"></i></a>
                                        </td>
                                        {% if product.item.discount_price %}
                                            <td class="cart__amount" style="font-size:15px;">
                                                GHC {{ product.sub_totaldisprice }} <span class="badge badge-danger">Saving {{ product.sub_totalsave }}</span>
                                            </td>
                                        {% else %}
                                            <td class="cart__amount" >GHC {{ product.sub_totalprice }}</td>
                                        {% endif %}
                                    </tr> 
                                {% endfor %}
                                <tr>
                                    <td colspan="3"></td>
                                    <td style="font-size:20px;"><b>Total: GHC {{ items.get_cart_total }}</b></td>
                                </tr>
                                <tf>
                                    <td colspan="4">
                                        <a href="{% url 'checkout' %}" class="btn btn-warning float-right ml-1 rounded-2">Checkout</a>
                                        <a href="{% url 'store' %}" class="btn btn-black btn-outline-black float-right ml-1 rounded-1">Keep shopping</a>
                                    </td>
                                    
                                </tf>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <br>
            
        {% endif %}
    </div>

{% endblock %}

templates/store/category.html
{% extends 'store/base.html' %}
{% block content %}
    <!--all product-->
  <div class="container" style="padding: 5rem 0;">
    <div class="heading_container">
      <h2>
        Category: 
      </h2>
    </div>
    <br>
    <div class="row">
      {% for item in products %}
      <div class="col-md-3"> <!-- Card -->
        <div class="card mb-4">
          <div class="view overlay">
            {% for img in item.productsimage_set.all %}
              {% if img.active %}
                <img src="{{ img.image.url }}" alt="" class="card-img-top m-2" height="200">
              {% endif %}
            {% endfor %}
          </div>
          <div class="card-body">
            <!-- Title -->
            <h5 class="card-title">{{ item.title }}</h5>
            <!-- Text -->
            {% if item.discount_price %}
              <p class="product-price">Ghc {{ item.discount_price }}  <del>Ghc {{ item.price }}</del></p>
            {% else %}
              <p class="product-price">Ghc {{ item.price }}</p>
            {% endif %}
            <!-- Button -->
            <a href="{% url 'detail' item.slug %}" class="btn btn-danger">View</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

templates/store/menu.html
{% load static %}
{% load cart_template_tags %}
<div class="container">
    <div class="hamburger-menu">
        <div class="line line-1"></div>
        <div class="line line-2"></div>
        <div class="line line-3"></div>
    </div>
</div>
<section class="sidebar">
    <ul class="menu">
        <li class="menu-item">
            <a href="/" class="menu-link" data-content="Home">Home</a>
        </li>
        <li class="menu-item">
            <a href="{% url 'store' %}" class="menu-link" data-content="Products">Products</a>
        </li>
        <li class="menu-item">
            <a href="{% url 'cart' %}" class="menu-link" data-content="Cart">Cart<span class="badge badge-light">{{ request.user|cart_item_count }}</span></a>
        </li>
        {% if user.is_authenticated %}
            <li class="menu-item">
                <a href="{% url 'profile' %}" class="menu-link" data-content="Blog">Profile</a>
            </li>
            <li class="menu-item">
                <a href="{% url 'logout' %}" class="menu-link" data-content="Blog">logout</a>
            </li>
        {% else %}
            <li class="menu-item">
                <a href="{% url 'login' %}" class="menu-link" data-content="Blog">Login/Register</a>
            </li>
        {% endif %}
        
    </ul>
    <div class="social-media">
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
</section>

templates/store/product.html
{% extends 'store/base.html' %}
{% block content %}
    <!--all product-->
  <div class="container" style="padding: 5rem 0;">
    <div class="heading_container">
      <h2>
        All Products
      </h2>
    </div>
    <br>
    <div class="row">
      {% for item in items %}
      <div class="col-md-3"> <!-- Card -->
        <div class="card mb-4">
          <div class="view overlay">
            {% for img in item.productsimage_set.all %}
              {% if img.active %}
                <img src="{{ img.image.url }}" alt="" class="card-img-top m-2" height="200">
              {% endif %}
            {% endfor %}
          </div>
          <div class="card-body">
            <!-- Title -->
            <h5 class="card-title">{{ item.title }}</h5>
            <!-- Text -->
            {% if item.discount_price %}
              <p class="product-price">Ghc {{ item.discount_price }}  <del>Ghc {{ item.price }}</del></p>
            {% else %}
              <p class="product-price">Ghc {{ item.price }}</p>
            {% endif %}
            <!-- Button -->
            <a href="{% url 'detail' item.slug %}" class="btn btn-danger">View</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

templates/store/search.html
{% extends 'base.html' %}
{% block content %}
    <!--all product-->
  <div class="container" style="padding: 5rem 0;">
    <div class="heading_container">
      <h2>
        Search for: {{ query }}
      </h2>
    </div>
    <br>
    <div class="row">
      {% for item in products %}
      <div class="col-md-3"> <!-- Card -->
        <div class="card mb-4">
          <div class="view overlay">
            {% for img in item.productsimage_set.all %}
              {% if img.active %}
                <img src="{{ img.image.url }}" alt="" class="card-img-top m-2" height="200">
              {% endif %}
            {% endfor %}
          </div>
          <div class="card-body">
            <!-- Title -->
            <h5 class="card-title">{{ item.title }}</h5>
            <!-- Text -->
            {% if item.discount_price %}
              <p class="product-price">Ghc {{ item.discount_price }}  <del>Ghc {{ item.price }}</del></p>
            {% else %}
              <p class="product-price">Ghc {{ item.price }}</p>
            {% endif %}
            <!-- Button -->
            <a href="{% url 'detail' item.slug %}" class="btn btn-danger">View</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

templates/store/searchbar.html
<nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand"></a>
    
    <form class="form-inline" action="{% url 'search' %}" method="GET">
      <input class="form-control mr-sm-3" type="search" placeholder="Search" name='q' aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </nav>

templates/store/singleproduct.html
{% extends "store/base.html" %}
{% block content %}
 <!-- Product Page Section Beign -->
    <section class="product-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <br>
                    <!--Carousel Wrapper-->
                    <div id="carousel-example-1z" class="carousel slide" data-ride="carousel">
                        <!--Indicators-->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-1z" data-slide-to="1"></li>
                            <li data-target="#carousel-example-1z" data-slide-to="2"></li>
                            <li data-target="#carousel-example-1z" data-slide-to="3"></li>
                        </ol>
                        <!--Slides-->
                        <div class="carousel-inner" role="listbox">
                            {% for img in product.productsimage_set.all %}
                                {% if forloop.counter == 1 %}
                                    <div class="carousel-item active">
                                {% else %}
                                    <div class="carousel-item">
                                {% endif %}
                                    <img class="d-block w-100" src="{{ img.image.url }}" alt="First slide" width="300", height="400">
                                </div>
                            {% endfor %}
                        </div>
                        
                        <!--Controls-->
                        <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                        <!--/.Controls-->
                    </div>
                    <br>  
                </div>
                <div class="col-lg-6">
                    <br>
                    <div class="product-content">
                        <h2>{{ product.title }}<span style="color:#24d278; float:right;"><i class="fas fa-star"></i></span></h2>
                        <div class="pc-meta">
                            {% if product.discount_price %}
                                <h5>Ghc {{ product.discount_price }}   <del><span class="btn-danger"> Ghc{{ product.price }}</span></del></h5>
                            {% else %}
                                <h5>Ghc {{ product.price }}</h5>
                            {% endif %}
                        </div>
                        <p>{{ product.description }}</p>
                        <ul class="tags">
                            <li><span>Category :</span>
                                {% for cat in product.category.all %}
                                <a href="{% url 'category' cat.title %}" class="btn btn-outline">{{ cat.title }}</a>
                                {% endfor %}
                            </li>
                        </ul>
                        <form action="{% url 'add_cart' product.slug %}" method="POST">
                            {% csrf_token %}
                            <ul class="tags">
                                <li><span>Quantity :
                                    <input class="form-control mb-5" type="number" value="1", name="qty">
                                </li>
                            </ul>
                            {% for vari in variations_set.all %}
                                {% if product.variations_set.all %}
                                    {% if product.variations_set.sizes %}
                                        <select class="form-control" name="size">
                                            {% for item in product.variations_set.sizes %}
                                                <option value="{{ item.id }}">{{ item.title|capfirst }}</option>
                                            {% endfor %} 
                                        </select>
                                    {% endif %}

                                    {% if product.variation_set.colors %}
                                        <select class="form-control" name="color">
                                                {% for item in product.variation_set.colors %}
                                                    <option value="{{ item.id }}">{{ item.title|capfirst }}</option>
                                                {% endfor %}
                                        </select>
                                    {% endif %}

                                    {% if product.variation_set.packages %}
                                        <select class="form-control" name="color">
                                                {% for item in product.variation_set.packages %}
                                                    <option value="{{ item.id }}">{{ item.title|capfirst }}</option>
                                                {% endfor %}
                                        </select>
                                    {% endif %}
                                {% endif %}     
                            {% endfor %}
                            <button class="btn btn-white btn-outline-black ml-1 rounded-1" type="submit" class="btn btn-black btn-outline-black ml-1 rounded-1">
                                Add To Cart
                            </button>
                            <button class="btn btn-white btn-outline-black ml-1 rounded-1">Like</button>
                        </form>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </section>

<!--product you may like-->
    <div class="container">
        <div class="heading_container">
            <h2>Related Products</h2>
        </div>
        <br>
        <div class="row">
            {% for item in related %}
            <div class="col-md-3"> 
                <!-- Card -->
                <div class="card mb-4">
                    <div class="view overlay">
                        {% for img in item.productsimage_set.all %}
                            {% if img.active %}
                                 <img src="{{ img.image.url }}" alt="" class="card-img-top m-2">
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name|capfirst }}</h5>
                            <!-- Text -->
                            {% if item.discount_price %}
                              <p class="product-price">Ghc {{ item.discount_price }} <del>Ghc {{ item.price }}</del></p>
                            {% else %}
                              <p class="product-price">Ghc {{ item.price }}</p>
                            {% endif %}
                        <a href="{% url 'detail' item.slug %}" class="btn btn-danger">View</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}